"""empty message

Revision ID: 38f8308da074
Revises: cce9bfcc68ee
Create Date: 2017-09-12 18:39:39.246383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f8308da074'
down_revision = 'cce9bfcc68ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chanels', ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'chanels', type_='unique')
    # ### end Alembic commands ###
