"""empty message

Revision ID: 8b9405abb021
Revises: 69e1490c3e0c
Create Date: 2017-09-15 01:05:56.927403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9405abb021'
down_revision = '69e1490c3e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('themename', sa.String(length=64), nullable=True),
    sa.Column('reference', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_themes_reference'), 'themes', ['reference'], unique=True)
    op.create_index(op.f('ix_themes_themename'), 'themes', ['themename'], unique=True)
    op.add_column('users', sa.Column('theme', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'themes', ['theme'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'theme')
    op.drop_index(op.f('ix_themes_themename'), table_name='themes')
    op.drop_index(op.f('ix_themes_reference'), table_name='themes')
    op.drop_table('themes')
    # ### end Alembic commands ###
