"""empty message

Revision ID: 91754701ffc2
Revises: 8b9405abb021
Create Date: 2017-09-15 12:13:45.015871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91754701ffc2'
down_revision = '8b9405abb021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'themes', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='unique')
    # ### end Alembic commands ###
