"""empty message

Revision ID: cce9bfcc68ee
Revises: eb9e0dd24670
Create Date: 2017-09-06 01:13:06.313638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce9bfcc68ee'
down_revision = 'eb9e0dd24670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chanels', ['id'])
    op.drop_constraint('follows_follower_id_fkey', 'follows', type_='foreignkey')
    op.drop_constraint('follows_rss_chanel_id_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'chanels', ['rss_chanel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_rss_chanel_id_fkey', 'follows', 'users', ['rss_chanel_id'], ['id'])
    op.create_foreign_key('follows_follower_id_fkey', 'follows', 'chanels', ['follower_id'], ['id'])
    op.drop_constraint(None, 'chanels', type_='unique')
    # ### end Alembic commands ###
