"""empty message

Revision ID: eb9e0dd24670
Revises: caa66703759c
Create Date: 2017-09-06 00:43:17.091630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9e0dd24670'
down_revision = 'caa66703759c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chanels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=1024), nullable=True),
    sa.Column('chanelname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_chanels_chanelname'), 'chanels', ['chanelname'], unique=True)
    op.create_index(op.f('ix_chanels_reference'), 'chanels', ['reference'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('rss_chanel_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['chanels.id'], ),
    sa.ForeignKeyConstraint(['rss_chanel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'rss_chanel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_index(op.f('ix_chanels_reference'), table_name='chanels')
    op.drop_index(op.f('ix_chanels_chanelname'), table_name='chanels')
    op.drop_table('chanels')
    # ### end Alembic commands ###
